import {chromium} from '@playwright/test';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173');await page.waitForTimeout(1200);await page.screenshot({path:'tests/overhead.png'});await page.keyboard.down('f');await page.waitForTimeout(800);const wingOpen=await page.evaluate(()=>window.__simulation.dorsalBody.motion.spread);await page.screenshot({path:'tests/wings-open.png'});await page.keyboard.up('f');await page.keyboard.press('f');await page.waitForTimeout(2600);const wingClosed=await page.evaluate(()=>window.__simulation.dorsalBody.motion.spread);const hindLengths=await page.evaluate(()=>window.__simulation.legs.slice(4).map(l=>[l.femurLength,l.tibiaLength]));if(wingOpen<.95||wingClosed>.01||hindLengths.some(([a,b])=>Math.abs(a-.891)>1e-6||Math.abs(b-1.111)>1e-6))throw new Error('Wing control or hind-leg length check failed');console.log(JSON.stringify({wingOpen,wingClosed,hindLengths}));await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.down('Shift');await page.waitForTimeout(500);await page.keyboard.down('a');await page.waitForTimeout(500);await page.keyboard.up('a');await page.keyboard.up('Shift');await page.keyboard.up('w');await page.waitForTimeout(600);const state=await page.evaluate(()=>({position:window.__simulation.controller.position.toArray(),speed:window.__simulation.controller.speed,yaw:window.__simulation.controller.yaw,legs:window.__simulation.legs.length,finite:window.__simulation.legs.every(l=>l.foot.toArray().every(Number.isFinite))}));await page.screenshot({path:'tests/contact-view.png'});console.log(JSON.stringify({errors,state}));if(errors.length||!state.finite||state.legs!==6||state.position[2]>-1)process.exitCode=1;
// Wasp tab: same controls drive the second specimen; wings unfold and fold back.
await page.getByRole('tab',{name:'Wasp'}).click();await page.waitForTimeout(800);await page.screenshot({path:'tests/wasp.png'});
await page.keyboard.down('f');await page.waitForTimeout(900);const waspOpen=await page.evaluate(()=>window.__simulation.dorsalBody.motion.spread);const buzzing=await page.evaluate(()=>document.querySelector('#state').textContent);await page.screenshot({path:'tests/wasp-wings.png'});await page.keyboard.up('f');await page.keyboard.press('f');await page.waitForTimeout(2600);const waspClosed=await page.evaluate(()=>window.__simulation.dorsalBody.motion.spread);
const start=await page.evaluate(()=>window.__simulation.controller.position.toArray());await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.down('d');await page.waitForTimeout(400);await page.keyboard.up('d');await page.keyboard.up('w');await page.waitForTimeout(400);
await page.keyboard.down('g');await page.waitForTimeout(900);const sting=await page.evaluate(()=>({level:window.__simulation.active.stingLevel,label:document.querySelector('#state').textContent,keys:[...document.querySelectorAll('.keys kbd')].map(k=>k.textContent).join(' ')}));await page.screenshot({path:'tests/wasp-sting.png'});await page.keyboard.up('g');await page.waitForTimeout(900);const sheathed=await page.evaluate(()=>window.__simulation.active.stingLevel);
// Wasp has no sprint: Shift must not raise speed above walking.
await page.keyboard.down('w');await page.keyboard.down('Shift');await page.waitForTimeout(900);const [waspTop,walkLimit]=await page.evaluate(()=>[window.__simulation.controller.speed,window.__simulation.params.walkSpeed]);await page.keyboard.up('Shift');await page.keyboard.up('w');await page.waitForTimeout(600);
const wasp=await page.evaluate(()=>({id:window.__simulation.active.id,title:document.title,selected:document.querySelector('[role=tab][aria-selected=true]').textContent,legs:window.__simulation.legs.length,finite:window.__simulation.legs.every(l=>l.foot.toArray().every(Number.isFinite)),position:window.__simulation.controller.position.toArray()}));
await page.getByRole('tab',{name:'Cockroach'}).click();await page.waitForTimeout(300);const back=await page.evaluate(()=>({id:window.__simulation.active.id,family:document.querySelector('h1').firstChild.textContent}));
console.log(JSON.stringify({waspOpen,waspClosed,buzzing,sting,sheathed,waspTop,wasp,back,errors}));
if(errors.length||wasp.id!=='wasp'||wasp.selected!=='Wasp'||wasp.legs!==6||!wasp.finite||wasp.position[2]>start[2]-1||waspOpen<.95||waspClosed>.01||buzzing!=='FLYING'||back.id!=='cockroach'||back.family!=='Blattodea'||sting.level<.95||sting.label!=='STINGING'||sting.keys!=='F C G'||sheathed>.05||waspTop>walkLimit+1e-6)process.exitCode=1;
await browser.close();
